FROM fedora:latest
RUN dnf upgrade -y
RUN dnf install -y gcc g++ ninja cmake git
RUN dnf install -y gtest-devel
RUN dnf install -y qt6-qtbase-devel qt6-qtdeclarative-devel qt6-qtserialbus-devel qt6-qtserialport-devel qt6-qtwebsockets-devel qt6-qttools-devel qt6-qtsvg-devel
RUN dnf install -y libgpiod-devel
